name: fluttermusic
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  audioplayers: ^0.20.1
  flutter_line_sdk: ^2.1.0
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NotoSansThai
      fonts:
        - asset: fonts/NotoSansThai-Regular.ttf
        - asset: fonts/NotoSansThai-Bold.ttf
